[instances]

[[instances.x]]
usernames = ["RockstarGames"]
discord_webhook_url = "https://discord.com/api/webhooks/XXXXXXXX/XXXXXXXX"
require_media = true
proxy = true
proxy_host = "xcancel.com"
proxy_name = "XCancel"

[[instances.x]]
usernames = ["CallofDuty"]
discord_webhook_url = "https://discord.com/api/webhooks/ZZZZZZZZ/ZZZZZZZZ"
exclude_keyword = ["warzone", "bundle"]
cooldown = 900
