[instances]

[[instances.x]]
usernames = ["RockstarGames"]
discord_webhook_url = "https://discord.com/api/webhooks/XXXXXXXX/XXXXXXXX"
require_media = true
archive = true
proxy = true
proxy_host = "twstalker.com"
proxy_name = "TwStalker"

[[instances.x]]
usernames = ["CallofDuty"]
discord_webhook_url = "https://discord.com/api/webhooks/ZZZZZZZZ/ZZZZZZZZ"
exclude_keyword = ["warzone", "bundle"]
cooldown = 900
retries = 3
retry_delay = 5.0
