[project]
name = "bluebird"
version = "3.0.0"
description = "Monitor users on X (Twitter) and report new posts via Discord."
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "EthanC", email = "16727756+EthanC@users.noreply.github.com" }]
dependencies = [
  "curl-cffi>=0.16.2",
  "discord-clyde>=1.0.0",
  "environs>=15.1.0",
  "loguru>=0.7.3",
  "loguru-discord>=2.1.0",
  "niquests>=3.21.0",
]

[dependency-groups]
dev = [
  "ruff>=0.16.4",
  "ty>=0.0.73",
]

[tool.ruff]
fix = true
show-fixes = true

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = ["I", "D"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.isort]
split-on-trailing-comma = false
