[project]
name = "bluebird"
version = "2.2.0"
description = "Monitor users on X (Twitter) and report new posts via Discord."
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "EthanC", email = "16727756+EthanC@users.noreply.github.com" }]
dependencies = [
  "discord-clyde>=1.0.0",
  "environs>=15.1.0",
  "httpx>=0.28.1",
  "loguru>=0.7.3",
  "loguru-discord>=2.1.0",
]

[dependency-groups]
dev = [
  "ruff>=0.16.4",
  "ty>=0.0.73",
]

[tool.ruff]
fix = true
show-fixes = true

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.uv]
package = false
