[project]
name = "bluebird"
version = "3.0.0"
description = "Monitor users on X (Twitter) and report new posts via Discord."
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "EthanC", email = "16727756+EthanC@users.noreply.github.com" }]
dependencies = [
  "archivist-py>=1.1.0",
  "discord-clyde>=1.1.0",
  "environs>=15.2.0",
  "loguru>=0.7.3",
  "loguru-discord>=2.1.0",
  "niquests>=3.21.1",
  "twscrape>=0.20.1",
]

[dependency-groups]
dev = [
  "coverage>=7.10.7",
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
  "ruff>=0.16.7",
  "ty>=0.0.81",
]

[tool.ruff]
fix = true
show-fixes = true

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = ["I", "D"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.pytest.ini_options]
addopts = "--strict-config --strict-markers"
pythonpath = ["."]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["core"]

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_covered = false

[tool.coverage.html]
directory = "htmlcov"

[tool.coverage.xml]
output = "coverage.xml"
