name: ci

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - id: repository
              uses: ASzc/change-string-case-action@v6
              with:
                  string: ${{ github.event.repository.name }}
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.repository.outputs.lowercase }}:latest
            - name: Docker Hub Description
              uses: peter-evans/dockerhub-description@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                  repository: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.repository.outputs.lowercase }}
                  short-description: ${{ github.event.repository.description }}
